-- Drop tables if they exist
DROP TABLE IF EXISTS Patients_New;

CREATE TABLE Patients_New (
    PatientId  CHAR(36) PRIMARY KEY,
    UHIDType VARCHAR(50) NOT NULL,
    UHIDNo VARCHAR(50),
    RegistrationDate DATE NOT NULL,
    RegistrationTime TIME NOT NULL,
    Sex VARCHAR(3) NOT NULL,
    PatientTitle VARCHAR(10) NOT NULL,
    PatientName VARCHAR(100) NOT NULL,
    DOB DATE,
    Age INT NOT NULL,
    GuardianTitle VARCHAR(10) NOT NULL,
    Guardian VARCHAR(100) NOT NULL,
    Address TEXT NOT NULL,
    Place VARCHAR(100),
    District VARCHAR(100),
    GSTState VARCHAR(100) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    PinCode VARCHAR(10),
    PatientAadhar VARCHAR(12),
    GuardianAadhar VARCHAR(12),
    MobileNo VARCHAR(15) NOT NULL,
    Email VARCHAR(100),
    Photo LONGBLOB,
    Occupation VARCHAR(100),
    MaritalStatus VARCHAR(50),
    BloodGroup VARCHAR(10),
    AllergicTo TEXT,
    ConsultantDoctor VARCHAR(100) NOT NULL,
    RefDoctor VARCHAR(100),
    PaymentTerms VARCHAR(100),
    RegistrationType VARCHAR(50),
    CompOrInsOrCamp VARCHAR(100),
    PatientCondition TEXT,
    ReferenceOrPicmeNo VARCHAR(15),
    IsActive BOOLEAN,
    CreatedBy VARCHAR(50),
    UpdatedBy VARCHAR(50),
    CreatedDate DATETIME,
    UpdatedDate DATETIME
);