
CREATE TABLE CommonMaster (
    CommonMasterId INT AUTO_INCREMENT PRIMARY KEY,
    MasterType VARCHAR(50) NOT NULL,
    MasterName VARCHAR(255) NOT NULL
);

INSERT INTO CommonMaster (MasterType, MasterName) VALUES
('category', '--No Category--'),
('complaint', '--No Complaint--'),
('complaint', 'ADMISSION'),
('complaint', 'CHECK UP'),
('complaint', 'DIABETIC'),
('complaint', 'EYE CHECKUP'),
('complaint', 'Fever'),
('complaint', 'GIDDINESS'),
('complaint', 'l+shoulder scold burning'),
('complaint', 'ORTHO'),
('complaint', 'POISSON'),
('complaint', 'spondylosis'),
('complaint', 'STOMACK PAIN'),
('complaint', 'UB PROBLEM'),
('complaint', 'VERTIGO'),
('complaint', 'VIRAL FEVER'),
('group', 'BIOCHEMISTRY'),
('group', 'CLINICAL PATHOLOGY'),
('group', 'CT-SCAN'),
('group', 'CYTOGENETICS'),
('group', 'CYTOLOGY'),
('group', 'DOPPLER'),
('group', 'DR.VIJAYARAJ MS'),
('group', 'ECG'),
('group', 'ECHO'),
('group', 'ENZYMES'),
('group', 'HAEMATOLOGY'),
('group', 'HISTOPATHOLOGY'),
('group', 'HORMONES'),
('group', 'HOSPITAL'),
('group', 'IMMUNOLOGY'),
('group', 'Laboratory'),
('group', 'Micro Biology'),
('group', 'NEBULIZER CHARGES'),
('group', 'OPG'),
('group', 'POISSON CASE'),
('group', 'REGISTRATION CHARGES'),
('group', 'room master'),
('group', 'SEROLOGY'),
('group', 'USG'),
('group', 'X-RAY'),
('packing', '--No Packing--'),
('section', '--No Section--'),
('section', 'CBC'),
('section', 'CT-SCAN'),
('section', 'CYTOGENETICS'),
('section', 'DOCTOR FEES'),
('section', 'DOPPLER'),
('section', 'ECG'),
('section', 'ECHO'),
('section', 'HOSPITAL'),
('section', 'ICU CHARGES'),
('section', 'LAB'),
('section', 'Laboratory'),
('section', 'NEBULIZER CHARGES'),
('section', 'No Section'),
('section', 'OPG'),
('section', 'OUT SIDE DR FEES'),
('section', 'REGISTRATION CHARGES'),
('section', 'SURGERY FEES'),
('section', 'USG'),
('section', 'X-RAY'),
('summarymaster', 'Complaints'),
('summarymaster', 'Diagnosis'),
('summarymaster', 'Past Iliness');
