-- Create table for ICD-10 Codes
CREATE TABLE icdcode_master (
	icdcodemasterId INT AUTO_INCREMENT PRIMARY KEY,
    icd_code VARCHAR(10) ,
    diagnosis_condition VARCHAR(255) NOT NULL,
    description_usage VARCHAR(255),
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT NOW(),
    UpdatedAt DATETIME DEFAULT NOW() ON UPDATE NOW()
);
INSERT INTO icdcode_master (icd_code, diagnosis_condition, description_usage, IsActive, CreatedAt, UpdatedAt)
VALUES
('A09', 'Infectious gastroenteritis and colitis', 'Common diarrheal diseases', TRUE, NOW(), NOW()),
('A15.0', 'Tuberculosis of lung', 'Pulmonary TB — high prevalence in India', TRUE, NOW(), NOW()),
('B20', 'HIV disease', 'HIV/AIDS cases', TRUE, NOW(), NOW()),
('C50.9', 'Malignant neoplasm of breast, unspecified', 'Common breast cancer code', TRUE, NOW(), NOW()),
('C61', 'Malignant neoplasm of prostate', 'Prostate cancer', TRUE, NOW(), NOW()),
('D50.9', 'Iron deficiency anemia, unspecified', 'Nutritional anemia — very common in India', TRUE, NOW(), NOW()),
('E03.9', 'Hypothyroidism, unspecified', 'Very common endocrine diagnosis', TRUE, NOW(), NOW()),
('E10.9', 'Type 1 diabetes mellitus without complications', 'Juvenile diabetes', TRUE, NOW(), NOW()),
('E11.9', 'Type 2 diabetes mellitus without complications', 'Most common diabetes diagnosis', TRUE, NOW(), NOW()),
('E66.9', 'Obesity, unspecified', 'Obesity-related conditions', TRUE, NOW(), NOW()),
('E78.5', 'Hyperlipidemia, unspecified', 'High cholesterol', TRUE, NOW(), NOW()),
('F32.9', 'Major depressive disorder, unspecified', 'Depression', TRUE, NOW(), NOW()),
('F41.1', 'Generalized anxiety disorder', 'Anxiety disorder', TRUE, NOW(), NOW()),
('G40.9', 'Epilepsy, unspecified', 'Seizure disorder', TRUE, NOW(), NOW()),
('G47.33', 'Obstructive sleep apnea (adult)', 'Sleep apnea', TRUE, NOW(), NOW()),
('H10.9', 'Conjunctivitis, unspecified', 'Eye infection', TRUE, NOW(), NOW()),
('H66.90', 'Otitis media, unspecified', 'Middle ear infection', TRUE, NOW(), NOW()),
('I10', 'Essential (primary) hypertension', 'High blood pressure', TRUE, NOW(), NOW()),
('I11.9', 'Hypertensive heart disease without heart failure', 'Cardiac complication of hypertension', TRUE, NOW(), NOW()),
('I20.9', 'Angina pectoris, unspecified', 'Chest pain due to ischemia', TRUE, NOW(), NOW()),
('I21.9', 'Acute myocardial infarction, unspecified', 'Heart attack', TRUE, NOW(), NOW()),
('I25.10', 'Atherosclerotic heart disease of native coronary artery', 'Coronary artery disease', TRUE, NOW(), NOW()),
('I48.91', 'Atrial fibrillation, unspecified', 'Irregular heartbeat', TRUE, NOW(), NOW()),
('I50.9', 'Heart failure, unspecified', 'Congestive heart failure', TRUE, NOW(), NOW()),
('I63.9', 'Cerebral infarction, unspecified', 'Ischemic stroke', TRUE, NOW(), NOW()),
('J00', 'Acute nasopharyngitis (common cold)', 'Common cold', TRUE, NOW(), NOW()),
('J06.9', 'Acute upper respiratory infection, unspecified', 'URTI — very common in India', TRUE, NOW(), NOW()),
('J18.9', 'Pneumonia, unspecified organism', 'Bacterial or viral pneumonia', TRUE, NOW(), NOW()),
('J20.9', 'Acute bronchitis, unspecified', 'Viral bronchitis', TRUE, NOW(), NOW()),
('J30.9', 'Allergic rhinitis, unspecified', 'Allergy-related nasal congestion', TRUE, NOW(), NOW()),
('J45.9', 'Asthma, unspecified', 'Asthma attack or chronic asthma', TRUE, NOW(), NOW()),
('J44.9', 'Chronic obstructive pulmonary disease, unspecified', 'COPD — smoker’s lung', TRUE, NOW(), NOW()),
('K21.9', 'Gastro-oesophageal reflux disease without oesophagitis', 'Acid reflux', TRUE, NOW(), NOW()),
('K29.70', 'Gastritis, unspecified', 'Stomach inflammation', TRUE, NOW(), NOW()),
('K58.9', 'Irritable bowel syndrome, unspecified', 'IBS symptoms', TRUE, NOW(), NOW()),
('K80.2', 'Calculus of gallbladder without cholecystitis', 'Gallstones', TRUE, NOW(), NOW()),
('K35.9', 'Acute appendicitis, unspecified', 'Appendicitis cases', TRUE, NOW(), NOW()),
('K64.4', 'Unspecified anal fissure', 'Rectal pain/bleeding', TRUE, NOW(), NOW()),
('L20.9', 'Atopic dermatitis, unspecified', 'Eczema', TRUE, NOW(), NOW()),
('L30.9', 'Dermatitis, unspecified', 'Skin rash', TRUE, NOW(), NOW()),
('L03.90', 'Cellulitis, unspecified', 'Skin infection', TRUE, NOW(), NOW()),
('M17.9', 'Osteoarthritis of knee, unspecified', 'Knee joint pain', TRUE, NOW(), NOW()),
('M19.90', 'Osteoarthritis, unspecified site', 'Degenerative joint disease', TRUE, NOW(), NOW()),
('M54.5', 'Low back pain', 'Very common complaint in OPD', TRUE, NOW(), NOW()),
('M25.50', 'Pain in unspecified joint', 'Joint pain', TRUE, NOW(), NOW()),
('M75.100', 'Rotator cuff tear, unspecified', 'Shoulder injury', TRUE, NOW(), NOW()),
('M79.1', 'Myalgia', 'Muscle pain', TRUE, NOW(), NOW()),
('N18.9', 'Chronic kidney disease, unspecified', 'CKD in various stages', TRUE, NOW(), NOW()),
('N39.0', 'Urinary tract infection, site not specified', 'UTI — very common', TRUE, NOW(), NOW()),
('N40.0', 'Benign prostatic hyperplasia', 'Enlarged prostate', TRUE, NOW(), NOW()),
('O80', 'Single spontaneous delivery', 'Normal delivery', TRUE, NOW(), NOW()),
('O82', 'Single delivery by caesarean section', 'C-section delivery', TRUE, NOW(), NOW()),
('O24.9', 'Diabetes mellitus in pregnancy, unspecified', 'Gestational diabetes', TRUE, NOW(), NOW()),
('O99.89', 'Other specified diseases complicating pregnancy', 'Pregnancy complication', TRUE, NOW(), NOW()),
('P07.30', 'Preterm newborn, unspecified weeks of gestation', 'Premature birth', TRUE, NOW(), NOW()),
('R10.4', 'Other and unspecified abdominal pain', 'Abdominal pain', TRUE, NOW(), NOW()),
('R11.0', 'Nausea', 'Feeling of sickness', TRUE, NOW(), NOW()),
('R51.9', 'Headache, unspecified', 'Common headache', TRUE, NOW(), NOW()),
('R53.83', 'Other fatigue', 'Weakness and tiredness', TRUE, NOW(), NOW()),
('R07.9', 'Chest pain, unspecified', 'Chest discomfort', TRUE, NOW(), NOW()),
('R42', 'Dizziness and giddiness', 'Vertigo symptoms', TRUE, NOW(), NOW()),
('R63.4', 'Abnormal weight loss', 'Weight loss unexplained', TRUE, NOW(), NOW()),
('R79.9', 'Abnormal finding of other biomarkers', 'Lab abnormality', TRUE, NOW(), NOW()),
('S83.401A', 'Sprain of right knee, initial encounter', 'Sports injury', TRUE, NOW(), NOW()),
('T78.40XA', 'Allergy, unspecified, initial encounter', 'Allergic reaction', TRUE, NOW(), NOW()),
('Z00.00', 'Encounter for general adult medical examination', 'Health check-up (normal)', TRUE, NOW(), NOW()),
('Z00.01', 'Encounter for adult medical examination with abnormal findings', 'Health check-up (with issues)', TRUE, NOW(), NOW()),
('Z00.129', 'Child health examination without abnormal findings', 'Routine child check-up', TRUE, NOW(), NOW()),
('Z00.121', 'Child health examination with abnormal findings', 'Child check-up (with abnormality)', TRUE, NOW(), NOW()),
('Z13.6', 'Screening for cardiovascular disorders', 'Preventive screening', TRUE, NOW(), NOW()),
('Z13.89', 'Screening for other disorders', 'Health screening', TRUE, NOW(), NOW()),
('Z20.9', 'Exposure to unspecified communicable disease', 'Infectious contact', TRUE, NOW(), NOW()),
('Z23', 'Immunization encounter', 'Vaccination visit', TRUE, NOW(), NOW()),
('Z79.4', 'Long term (current) use of insulin', 'Chronic diabetes management', TRUE, NOW(), NOW()),
('Z95.1', 'Presence of aortocoronary bypass graft', 'History of CABG surgery', TRUE, NOW(), NOW()),
('Z86.73', 'Personal history of circulatory system disease', 'History of stroke/heart disease', TRUE, NOW(), NOW()),
('Z87.891', 'Personal history of nicotine dependence', 'Ex-smoker', TRUE, NOW(), NOW()),
('Z91.19', 'Noncompliance with medical treatment', 'Missed medications', TRUE, NOW(), NOW()),
('Z55.9', 'Problems related to education and literacy', 'Social determinant of health', TRUE, NOW(), NOW()),
('Z63.5', 'Disruption of family by separation or divorce', 'Psychosocial stress', TRUE, NOW(), NOW()),
('Z71.9', 'Counselling, unspecified', 'General medical counselling', TRUE, NOW(), NOW()),
('Z38.00', 'Single liveborn infant, delivered vaginally', 'Birth record', TRUE, NOW(), NOW()),
('Z48.01', 'Encounter for surgical wound dressing change', 'Post-surgery care', TRUE, NOW(), NOW()),
('Z51.81', 'Encounter for therapeutic drug monitoring', 'Lab follow-up', TRUE, NOW(), NOW()),
('Z68.25', 'BMI 35.0–35.9, adult', 'Obesity classification', TRUE, NOW(), NOW()),
('Z68.30', 'BMI 30.0–30.9, adult', 'Mild obesity', TRUE, NOW(), NOW()),
('Z79.899', 'Other long term (current) drug therapy', 'Chronic medication use', TRUE, NOW(), NOW()),
('Z63.0', 'Problems in relationship with spouse or partner', 'Marital stress', TRUE, NOW(), NOW()),
('Z76.9', 'Person encountering health services in unspecified circumstances', 'Administrative visit', TRUE, NOW(), NOW());
