CREATE TABLE Prescriptions (
    PrescriptionId INT AUTO_INCREMENT PRIMARY KEY,
    EntryType VARCHAR(50),
    EntryNo VARCHAR(20),
    EntryDate DATETIME,
    UHID VARCHAR(20),
    PatientName VARCHAR(100) NOT NULL,
    Address VARCHAR(200),
    Place VARCHAR(100),
    CellNo VARCHAR(20),
    Sex VARCHAR(10),
    Age INT,
    BloodGroup VARCHAR(10),
    HeightCm DECIMAL(5,2),
    WeightKg DECIMAL(5,2),
    BMI DECIMAL(5,2),
    Temperature DECIMAL(5,2),
    BP VARCHAR(20),
    SPO2 DECIMAL(5,2),
    PulseRate INT,
    ConsultBy VARCHAR(100),
    ReferredBy VARCHAR(100),
    Disease VARCHAR(100),
    Remarks VARCHAR(200),
    TotalAmount DECIMAL(10,2),
    NextVisitAfter INT,
    NextVisitDate DATETIME
);
