CREATE TABLE ProductMaster (
    ProductCode INT AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    GenericName VARCHAR(255),
    ProductGroup_List VARCHAR(255),
    ProductGroup_Txt VARCHAR(255),
    PurchaseUnit_List VARCHAR(255),
    PurchaseUnit_Txt VARCHAR(255),
    Packing INT,
    StockUnit_List VARCHAR(255),
    StockUnit_Txt VARCHAR(255),
    Rack_List VARCHAR(255),
    Rack_Txt VARCHAR(255),
    Bin_List VARCHAR(255),
    Bin_Txt VARCHAR(255),
    ProductType_List VARCHAR(255),
    ProductType_Txt VARCHAR(255),
    Manufacturer_List VARCHAR(255),
    Manufacturer_Txt VARCHAR(255),
    Remarks TEXT,
    PurchaseRate DECIMAL(18, 2),
    PurchaseDiscount DECIMAL(18, 2),
    MRP DECIMAL(18, 2),
    SaleRate DECIMAL(18, 2),
    SaleDiscount DECIMAL(18, 2),
    TaxPercent DECIMAL(5, 2),
    HSN VARCHAR(20),
    MinStock DECIMAL(18, 2),
    MaxStock DECIMAL(18, 2),
    MinOrder DECIMAL(18, 2),
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
